### PR TITLE
fixed #273 - resolvecontainer fix

### LINKED ISSUE #273: resolveContainer doesn't resolve in order of registration. It should return the last registered container with successful condition.

### PR DESCRIPTION
**Pull request by anubhavbisaria**
1. resolve Container resolves the last container instead of first
2. fixed the test to mockContainer

### CODE REVIEW

File: packages/desktopjs/src/registry.ts [hunk 1]
```diff
@@ -18,11 +18,11 @@ export class ContainerRegistration {
     create: (options?: any) => Container;
 }
 
-const registeredContainers: Map<string, ContainerRegistration> = new Map();
+const registeredContainers: {id: string, registration: ContainerRegistration}[] = [];
 
 /** Clears all container registrations. */
 export function clearRegistry() {
-    registeredContainers.clear();
+    registeredContainers.splice(0, registeredContainers.length - 1);
```
Comment (psmulovics) [inline packages/desktopjs/src/registry.ts]: Should we not keep the semantic of clear?

Comment (anubhavbisaria) [reply packages/desktopjs/src/registry.ts]: I am not sure what you mean. registeredContainers was a Map, so clear just emptied the map, same as splice for Array.

Comment (psmulovics) [reply packages/desktopjs/src/registry.ts]:
```
var months = ['Jan', 'March', 'April', 'June'];
months.splice(0, months.length - 1);
console.log(months);
```

This returns ["June"] instead of [].

Comment (anubhavbisaria) [reply packages/desktopjs/src/registry.ts]: oh yeah, this was fixed in subsequent commit.

File: packages/desktopjs/src/registry.ts [hunk 2]
```diff
@@ -68,16 +68,18 @@ export function resolveContainer(param1?: boolean | any, param2?: any): Containe
...
-    for (const entry in registeredContainers) {
-        try {
-            if (registeredContainers[entry].condition(options)) {
-                return container = registeredContainers[entry].create(options);
-            }
-        } catch (e) {
-            console.error("Error resolving container '" + entry + "': " + e.toString());
+    let registration: ContainerRegistration;
+    try {
+        for (let i: number =0; i< registeredContainers.length; i++) { // tslint:disable-line
```
Comment (bingenito) [inline packages/desktopjs/src/registry.ts]: What doesn't tslint like here?

Comment (anubhavbisaria) [reply packages/desktopjs/src/registry.ts]: because it has a rule saying prefer for..in

File: packages/desktopjs/src/registry.ts [hunk 3]
```diff
@@ -68,16 +68,18 @@ export function resolveContainer(param1?: boolean | any, param2?: any): Containe
...
+            const testReg: ContainerRegistration = registeredContainers[i].registration;
+            registration = testReg.condition(options) ? testReg : registration;
         }
+        container = registration.create(options);
+    } catch (e) {
+        console.error(`Error resolving container : ${e.toString()}`);
```
Comment (bingenito) [inline packages/desktopjs/src/registry.ts]: This lost the name of the container which failed to resolve.  Can you add the registry name back in?
