### PR TITLE
ContainerWindow getBounds/setBounds

### LINKED ISSUE #45: Browser layout persistence is incorrectly using inner vs outerWidth/Height

### LINKED ISSUE #46: Add ContainerWindow getBounds and setBounds

### PR DESCRIPTION
**Pull request by bingenito**
Fixes #45
Fixes #46

### CODE REVIEW

File: src/Electron/electron.ts [hunk 1]
```diff
@@ -275,7 +288,10 @@ export class ElectronContainer extends WebContainerBase {
     }
 
     public getAllWindows(): Promise<ContainerWindow[]> {
-        return Promise.resolve(this.browserWindow.getAllWindows().map(window => this.wrapWindow(window)));
```
Comment (psmulovics) [inline src/Electron/electron.ts]: Probably this should be in a separate PR
